FROM centos:centos7

RUN yum update -y
RUN yum install nginx -y

RUN mkdir -p /usr/share/nginx/html/traefik/dashboard
COPY static/ /usr/share/nginx/html/traefik/dashboard
COPY nginx.conf.template /etc/nginx/nginx.conf
RUN rm -rf /usr/share/nginx/html/index.html
RUN ln -s /usr/share/nginx/html/traefik/dashboard/index.html /usr/share/nginx/html/index.html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
